### ISSUE TITLE
Power networks don't work

### ISSUE THREAD

**Issue by Fulgen301** [minetest-mods/technic#386]
Although having a solar panel, a battery box and an energy consumer connected, all items can't find a power network.

**Comment by numberZero** [comment]
@Fulgen301 RTFM. You need a switching station.

**Comment by Fulgen301** [comment]
I did read it. It doesn't work with a switching station.
[http://imgur.com/a/qri1I](http://imgur.com/a/qri1I)

**Comment by DS-Minetest** [comment]
Have you tried placing the switching station somewhere else? I recognized that sometimes it doesn't work on mapblock boarders.

**Comment by Fulgen301** [comment]
Yes, I did, same result.

**Comment by numberZero** [comment]
That is, we have a problem.
@Fulgen301 what’s the technic version you use?

**Comment by numberZero** [comment]
And what does the switching station itself display when you point at it?

**Comment by Fulgen301** [comment]
Okay, I built a network which didn't work, then I went building a house. After I returned, suddenly the battery, the switching station and the solar array worked, but the force field emitter still doesn't find a network, although being connected.
I use the current master branch (a84b5f3b28789318738dfa52ee1264c8d31eecb4)

**Comment by thatgraemeguy** [comment]
The force field requires 10,000HV to run. A single HV array placed at the optimal height (i.e. not on the ground like yours) only makes 5,000HV. What you will see in that situation is that the battery will be charged by the HV array until it has at least 10,000HV, then the force field will run, but only briefly because it will drain the battery almost immediately. If you want the force field to run continuously you need at least 10,000HV supplied continuously.
