### ISSUE TITLE
Use official register_ore APIs in technic_worldgen to avoid OOMs?

### ISSUE THREAD

**Issue by Fixer-007** [minetest-mods/technic#413]
There is official api for generating ores and stuff, Paramat says it is OOM free, done in engine, why not use it?

Details here:
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L4985
https://github.com/minetest/minetest/blob/master/doc/lua_api.txt#L1143

**Comment by numberZero** [comment]
@Fixer-007 explain please. https://github.com/minetest-mods/technic/blob/master/technic_worldgen/oregen.lua is full of `register_ore`

**Comment by Fixer-007** [comment]
You are right, I was too lazy to check, question is WTH it gives OOM?

**Comment by numberZero** [comment]
@Fixer-007 Dunno. That may be sulfur generation (which does use register_on_generated and not register_ore), but it can’t be done the other way AFAIK. Or there may be something else, interfering with technic. You gave way too little info (well I know, Lua doesn’t dump a lot in the case of OOM. But it does dump *something*, doesn’t it?)

**Comment by Fixer-007** [comment]
@numberZero Both technic worldgen and darkage mapgen give me OOM with On_generated in error.

**Comment by Fixer-007** [comment]
More news about optimisations here:
https://forum.minetest.net/viewtopic.php?f=18&t=16043#p314553
https://forum.minetest.net/viewtopic.php?f=18&t=16043#p242631
https://forum.minetest.net/viewtopic.php?f=18&t=19836

**Comment by numberZero** [comment]
@Fixer-007 I know that, thanks. Technic worldgen uses these optimizations. The only place in it where memory could leak (temporarily, it’s Lua) I see is table creation in `sulfur_noise:get3d({x = x, y = z, z = z})`.
Darkage mapgen, on the other hand, doesn’t use these. If you use both mods simultaneously, it may fill memory *almost* completely, so that the remaining amount is not enough for techinc worldgen, so it gives OOM despite using less memory. Have you tested them separately?
