### ISSUE TITLE
Blunt Chainsaw

### ISSUE THREAD

**Issue by MidnightPhantom** [minetest-mods/technic#619]
In the latest releases of this mod, I have encountered a really weird issue. I crafted a chainsaw and then was trying to chop wood for my needs, but out of nowhere I get to know that the tree I was trying to chop wasn't breaking down, I thought that the battery was low but when I looked at it, it was full, aka there was a light green bar below it. So I tried to chop it again, but the tree won't break, then I went to recharge it. After recharging I went back to cut another tree of the same kind, but even that tree won't cut. The next thing I remembered doing was using the chainsaw on every tree in the base game and came up with the following conclusion.

The trees this thing cuts
Pine, Aspen

The tree this weird tool randomly cuts
Apple, acacia, and jungle.

**Comment by SmallJoker** [comment]
@MidnightPhantom This is likely caused by rotated schematics that are placed in the world, resulting in param2 values (rotation) along the Z axis. Usually that value is 0 for generated trees, thus it can be used to avoid accidental cutting of blocks placed by players.

https://github.com/minetest-mods/technic/blob/0921c326a8f1b6ffc5e8013e3c477983df96f386/technic/tools/chainsaw.lua#L127-L131

By removing those lines, the trees should again be cut but I do not know whether removing this protection is a good idea.

**Comment by MidnightPhantom** [comment]
Thanks for providing that info.
And for safety, you can turn it into settings

**Comment by SmallJoker** [comment]
dfcf64c
